import { Schema, Document, Types } from 'mongoose';

export interface AssetDocument extends Document {
  tenantId: Types.ObjectId;
  url: string;
  filename: string;
  type: 'image' | 'video' | 'text' | 'other';
  tags: string[];
  categories?: string[]; // For asset library organization
  metadata: {
    contentType?: string;
    size?: number;
    width?: number;
    height?: number;
    duration?: number;
    aiModel?: string; // If generated by AI
    generatedPrompt?: string;
    [key: string]: any;
  };
  uploadedBy: string;
  uploadedAt: Date;
  lastUrlRefreshAt?: Date; // Track when URL was last refreshed
  urlExpiresAt?: Date; // When signed URL expires (if applicable)
  isPermanent?: boolean; // True if using public URL (no expiration)
  usedInCampaigns: Types.ObjectId[];
  usedInContentVersions: Array<{
    campaignId: Types.ObjectId;
    version: number;
  }>;
  usedInStrategyVersions?: Array<{
    campaignId: Types.ObjectId;
    version: number;
  }>; // Track which strategy versions used this asset
  replacedBy?: string;
  archived: boolean;
  archivedAt?: Date;
}

export const AssetSchema = new Schema<AssetDocument>({
  tenantId: { type: Schema.Types.ObjectId, ref: 'Tenant', required: true },
  url: { type: String, required: true },
  filename: { type: String, required: true },
  type: { type: String, enum: ['image', 'video', 'text', 'other'], default: 'other' },
  tags: { type: [String], default: [] },
  categories: { type: [String], default: [] },
  metadata: { type: Object, default: {} },
  uploadedBy: { type: String, required: true },
  uploadedAt: { type: Date, default: Date.now },
  lastUrlRefreshAt: { type: Date },
  urlExpiresAt: { type: Date },
  isPermanent: { type: Boolean, default: false },
  usedInCampaigns: [{ type: Schema.Types.ObjectId, ref: 'Campaign' }],
  usedInContentVersions: [{
    campaignId: { type: Schema.Types.ObjectId, ref: 'Campaign' },
    version: { type: Number }
  }],
  usedInStrategyVersions: [{
    campaignId: { type: Schema.Types.ObjectId, ref: 'Campaign' },
    version: { type: Number }
  }],
  replacedBy: { type: String },
  archived: { type: Boolean, default: false },
  archivedAt: { type: Date },
});

// Indexes for efficient querying
AssetSchema.index({ tenantId: 1, tags: 1 });
AssetSchema.index({ tenantId: 1, type: 1 });
AssetSchema.index({ tenantId: 1, categories: 1 });
AssetSchema.index({ tenantId: 1, archived: 1 });
AssetSchema.index({ tenantId: 1, isPermanent: 1 });
AssetSchema.index({ tenantId: 1, urlExpiresAt: 1 });
AssetSchema.index({ 'usedInCampaigns': 1 });